# Generated by Django 4.2.7 on 2023-11-23 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book_reading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatistics",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
