version: "3.10"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  reading-time-accounting-system:
    tty: true
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - db
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    command: >
      sh -c "python manage.py db_connection &&
             celery -A config worker --loglevel=info"
#    command: "celery -A config worker -l info"
    depends_on:
      - db
      - redis
      - reading-time-accounting-system

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A config beat -l INFO"
    depends_on:
      - db
      - redis
      - reading-time-accounting-system
